// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, Link, matchPath, matchRoutes, Navigate, NavLink, Outlet, useLocation, useMatch, useNavigate, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, renderClient, useRouteData } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// plugins
export { connect, useDispatch, useStore, useSelector } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-dva';
export { KeepAliveContext, useKeepOutlets } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-keepalive';
export { getPageNavBar, setPageNavBar, setTabBarList, getTabBarList, layoutEmitter } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-mobile-layout';
export { Provider, useModel } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-model';
export { request, useRequest } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-dva/types.d';
export * from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-mobile-layout/types.d';
export * from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-request/types.d';
