// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { request } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/node_modules/@alita/request';
export { useRequest } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/node_modules/ahooks';
