// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { ResponseError,Context } from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/node_modules/@alita/request';
