// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// It's faked dva
// aliased to @umijs/plugins/templates/dva
import { create, Provider } from 'dva';
import React, { useRef } from 'react';
import { history } from 'umi';
import { models } from './models';

export function RootContainer(props: any) {
  const app = useRef<any>();
  if (!app.current) {
    app.current = create(
      {
        history,
      },
      {
        initialReducer: {},
        setupMiddlewares(middlewares: Function[]) {
          return [...middlewares];
        },
        setupApp(app: IDvaApp) {
          app._history = history;
        },
      },
    );
    for (const id of Object.keys(models)) {
      app.current.model(models[id].model);
    }
    app.current.start();
  }
  return <Provider store={app.current!._store}>{props.children}</Provider>;
}
