// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// Created by Umi Plugin

export interface IConfigFromPlugins {
title?: string
styles?: any[]
scripts?: any[]
routes?: {

}[]
presets?: string[]
plugins?: string[]
npmClient?: ("pnpm" | "tnpm" | "cnpm" | "yarn" | "npm")
mountElementId?: string
metas?: any[]
links?: any[]
history?: {
type?: ("browser" | "hash" | "memory")
}
headScripts?: any[]
conventionRoutes?: {
base?: string
exclude?: any[]
}
base?: string
writeToDisk?: boolean
theme?: {

}
targets?: {

}
svgr?: {

}
svgo?: ({

} | boolean)
styleLoader?: {

}
srcTranspiler?: ("babel" | "esbuild" | "swc" | "none")
sassLoader?: {

}
runtimePublicPath?: {

}
purgeCSS?: {

}
publicPath?: string
proxy?: {

}
postcssLoader?: {

}
outputPath?: string
mfsu?: ({
cacheDirectory?: string
chainWebpack?: (() => any)
esbuild?: boolean
mfName?: string
runtimePublicPath?: boolean
} | boolean)
mdx?: {
loader?: string
loaderOptions?: {

}
}
manifest?: {

}
lessLoader?: {

}
jsMinifierOptions?: {

}
jsMinifier?: ("esbuild" | "swc" | "terser" | "uglifyJs" | "none")
inlineLimit?: number
ignoreMomentLocale?: boolean
https?: {

}
hash?: boolean
forkTSChecker?: {

}
fastRefresh?: boolean
extraPostCSSPlugins?: any[]
extraBabelPresets?: any[]
extraBabelPlugins?: any[]
extraBabelIncludes?: string[]
externals?: ({

} | string | (() => any))
esm?: {

}
devtool?: (string | boolean)
depTranspiler?: ("babel" | "esbuild" | "swc" | "none")
define?: {

}
deadCode?: {

}
cssMinifierOptions?: {

}
cssMinifier?: ("cssnano" | "esbuild" | "parcelCSS" | "none")
cssLoaderModules?: {

}
cssLoader?: {

}
copy?: any[]
chainWebpack?: (() => any)
autoprefixer?: {

}
autoCSSModules?: boolean
alias?: {

}
crossorigin?: (boolean | {
include?: {

}[]
})
esmi?: {
cdnOrigin?: string
shimUrl?: string
}
favicon?: string
mock?: {
exclude?: string[]
include?: string[]
}
polyfill?: {
imports?: string[]
}
terminal?: {

}
tmpFiles?: boolean
lowImport?: {
libs?: any[]
css?: string
}
vite?: {

}
apiRoute?: {
platform?: string
}
monorepoRedirect?: (boolean | {
srcDir?: string[]
exclude?: {

}[]
})
verifyCommit?: {
scope?: string[]
allowEmoji?: boolean
}
retainLog?: boolean
complexRoute?: boolean
packageId?: string
displayName?: string
displayIcon?: string
appType?: ("h5" | "pc" | "docs" | "cordova" | "micro" | "native")
aconsole?: {
inspx?: {
disabled?: boolean
production?: boolean
margin?: boolean
size?: boolean
padding?: boolean
bottom?: string
right?: string
}
console?: {
defaultPlugins?: any[]
onReady?: (() => any)
onClearLog?: (() => any)
maxLogNumber?: number
disableLogScrolling?: boolean
theme?: string
}
}
keepalive?: any[]
mainPath?: string
request?: {

}
dva?: {
extraModels?: string[]
enableModelsReExport?: boolean
}
model?: {
extraModels?: string[]
}
hd?: {
theme?: {

}
px2rem?: {

}
}
mobileLayout?: (boolean | string)
}
