// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as Plugin_0 from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/app.tsx';
import * as Plugin_1 from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-aconsole/runtime.tsx';
import * as Plugin_2 from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-keepalive/runtime.tsx';
import * as Plugin_3 from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-dva/runtime.tsx';
import * as Plugin_4 from '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-model/runtime.tsx';
import { PluginManager } from 'umi';

export function getPlugins() {
  return [
    {
      apply: Plugin_0,
      path: '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/app.tsx',
    },
    {
      apply: Plugin_1,
      path: '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-aconsole/runtime.tsx',
    },
    {
      apply: Plugin_2,
      path: '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-keepalive/runtime.tsx',
    },
    {
      apply: Plugin_3,
      path: '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-dva/runtime.tsx',
    },
    {
      apply: Plugin_4,
      path: '/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-model/runtime.tsx',
    },
  ];
}

export function getValidKeys() {
  return ['patchRoutes','patchClientRoutes','modifyContextOpts','rootContainer','innerProvider','i18nProvider','accessProvider','dataflowProvider','outerProvider','render','onRouteChange','request','mobileLayout',];
}

let pluginManager = null;
export function createPluginManager() {
  pluginManager = PluginManager.create({
    plugins: getPlugins(),
    validKeys: getValidKeys(),
  });
  return pluginManager;
}

export function getPluginManager() {
  return pluginManager;
}
