// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export async function getRoutes() {
  return {
    routes: {"message/index":{"path":"message","id":"message/index","parentId":"alita-layout","file":"message/index.tsx"},"my/index":{"path":"my","id":"my/index","parentId":"alita-layout","file":"my/index.tsx"},"index":{"path":"/","id":"index","parentId":"alita-layout","file":"index.tsx"},"alita-layout":{"id":"alita-layout","path":"/","file":"/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-mobile-layout/AlitaLayout.tsx"}},
    routeComponents: {
'message/index': () => import('../../../src/pages/message/index.tsx'),
'my/index': () => import('../../../src/pages/my/index.tsx'),
'index': () => import('../../../src/pages/index.tsx'),
'alita-layout': () => import('/Users/damon/Documents/thundersdata/frontend/react-universal-template/packages/h5/src/.umi/plugin-mobile-layout/AlitaLayout.tsx'),
},
  };
}
